### ISSUE TITLE
Error trying to resolve when using AddNavigationConnectionField()

### ISSUE THREAD

**Issue by rossdonald** [SimonCropp/GraphQL.EntityFramework#162]
Hi, I have been checking out this library and I have it working on a test project for non-connection queries.

I am getting an error using `AddNavigationConnectionField()` when trying to get a list of paged orders for a customer.

```
"GraphQL.ExecutionError: Error trying to resolve customers. ---> System.Collections.Generic.KeyNotFoundException: The given key 'System.Object' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at IncludeAppender.AddField(List`1 list, Field field, String parentPath, FieldType fieldType, List`1 parentNavigationProperties) in src\GraphQL.EntityFramework\IncludeAppender.cs:line 76
   at IncludeAppender.ProcessSubFields(List`1 list, String parentPath, ICollection`1 subFields, IComplexGraphType complexGraph, List`1 navigationProperties) in src\GraphQL.EntityFramework\IncludeAppender.cs:line 96
   at IncludeAppender.GetPaths(FieldType fieldType, ICollection`1 fields, List`1 navigationProperty) in src\GraphQL.EntityFramework\IncludeAppender.cs:line 43
   at IncludeAppender.AddIncludes[T](IQueryable`1 query, FieldType fieldType, ICollection`1 subFields, List`1 navigationProperties) in src\GraphQL.EntityFramework\IncludeAppender.cs:line 29
   at IncludeAppender.AddIncludes[TItem,TSource](IQueryable`1 query, ResolveFieldContext`1 context) in src\GraphQL.EntityFramework\IncludeAppender.cs:line 20
   at GraphQL.EntityFramework.EfGraphQLService`1.<>c__DisplayClass21_0`2.<<BuildQueryField>b__0>d.MoveNext() in src\GraphQL.EntityFramework\GraphApi\EfGraphQLService_Queryable.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at GraphQL.Instrumentation.MiddlewareResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)
   --- End of inner exception stack trace ---"
```
   
When I step in to the code in ComplexGraphResolver I can see in `GetOrAdd(FieldType fieldType)` that when it is trying to resolve the ConnectionType<OrdersType> then `resolved.EntityType` is resolved as "object".

If I use the debugger and set this to typeof(Orders) (my model type) then there is no error and my query returns correctly.

Not sure if this is an error with my config or a bug.

**Comment by SimonCropp** [comment]
Did you read the issue template?

**Comment by rossdonald** [comment]
I did read the template. Do you want a repro project?

**Comment by SimonCropp** [comment]
Yep

And the bit about being a patron https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

And how far did u get with an attempted fix?

**Comment by rossdonald** [comment]
I have looked at it further. This issue happens with the SampleWeb project that is part of this repo.
There isn't a test that covers AddNavigationConnectionField() so I added one.
  
The issue seems to be to do with the Relay types in graphql-dotnet are defined like this:
  
```
namespace GraphQL.Types.Relay
{
    public class ConnectionType<TNodeType, TEdgeType> : ObjectGraphType<object>
//...
public class EdgeType<TNodeType> : ObjectGraphType<object>
//..		
public class PageInfoType : ObjectGraphType<object>

```		
[/Types/Relay/ConnectionType.cs](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Relay/ConnectionType.cs)

so that when the `ResolvedEntityType()` method in ComplexGraphResolver loops past `ConnectionType` down to `ComplexGraphType` then the generic argument is always "object"

I am not great with generics but if ConnectionType etc passed the type to ObjectGraphType like this it might fix the issue:

`public class ConnectionType<TNodeType, TEdgeType> : ObjectGraphType<TNodeType>`
		
or perhaps `ResolvedEntityType()` needs to accommodate these Relay types somehow?

**Comment by SimonCropp** [comment]
the tests for sample web are more about verifying the interaction with aspnet core. most tests exist in https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/src/Tests/IntegrationTests/IntegrationTests.cs so if you want do do a "failing test PR" you should add it there

And the bit about being a patron? https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
