### ISSUE TITLE
Unable to resolve service for type 'GraphQL.EntityFramework.IEfGraphQLService`

### ISSUE THREAD

**Issue by PayteR** [SimonCropp/GraphQL.EntityFramework#295]
#### Describe the issue

After update project to .Core 3.0 i can't resolve `IEfGraphQLService` , whole error is here

```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: ProjectGraphQlTest.API.Schema.Query Lifetime: Singleton ImplementationType: ProjectGraphQlTest.API.Schema.Query': Unable to resolve service for type 'GraphQL.EntityFramework.IEfGraphQLService`1[ProjectGraphQlTest.Infrastructure.Data.AppDbContext]' while attempting to activate 'ProjectGraphQlTest.API.Schema.Query'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ProjectGraphQlTest.Program.Main(String[] args) in D:\dotnet\SimpliX\ProjectGraphQlTest\Program.cs:line 16

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: ProjectGraphQlTest.API.Schema.Query Lifetime: Singleton ImplementationType: ProjectGraphQlTest.API.Schema.Query': Unable to resolve service for type 'GraphQL.EntityFramework.IEfGraphQLService`1[ProjectGraphQlTest.Infrastructure.Data.AppDbContext]' while attempting to activate 'ProjectGraphQlTest.API.Schema.Query'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'GraphQL.EntityFramework.IEfGraphQLService`1[ProjectGraphQlTest.Infrastructure.Data.AppDbContext]' while attempting to activate 'ProjectGraphQlTest.API.Schema.Query'.
```

#### Minimal Repro

Minimal repo is here https://github.com/PayteR/ProjectGraphQlTest

**Comment by PayteR** [comment]
I was missing this in ConfigureServices()

```
EfGraphQLConventions.RegisterInContainer<AppDbContext>(
                services,
                model: AppDbContext.StaticModel);
```
