### ISSUE TITLE
GraphQL.ExecutionError: Error trying to resolve customers. ---> System.MissingMethodException: Method not found: 'System.Object GraphQL.Types.ResolveFieldContext`1.get_UserContext()'

### ISSUE THREAD

**Issue by thesobercoder** [SimonCropp/GraphQL.EntityFramework#328]
https://opencollective.com/soham-dasgupta

Error executing query with the following stack trace -

```
GraphQL.ExecutionError: Error trying to resolve customers.
---> System.MissingMethodException: Method not found: 'System.Object GraphQL.Types.ResolveFieldContext`1.get_UserContext()'.
at GraphQL.EntityFramework.EfGraphQLService`1.<>c__DisplayClass26_0`2.<<BuildQueryField>b__0>d.MoveNext()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at GraphQL.EntityFramework.EfGraphQLService`1.<>c__DisplayClass26_0`2.<BuildQueryField>b__0(ResolveFieldContext`1 context)
at GraphQL.Instrumentation.MiddlewareResolver.Resolve(ResolveFieldContext context)
at GraphQL.Instrumentation.InstrumentFieldsMiddleware.Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)
```

The code can be found at the following repo - 

https://github.com/thesobercoder/GraphQLTest

**Comment by SimonCropp** [comment]
can u share that repro by placing it in a gh repo.

**Comment by thesobercoder** [comment]
@SimonCropp I've updated the description with the github repo. Thanks.

**Comment by SimonCropp** [comment]
@thesobercoder ok the problem is you are using a preview of GraphQL with breaking changes. do you need functionality from the preview?

**Comment by thesobercoder** [comment]
@SimonCropp I don't think so. I'll revert back to stable release for now for all the packages. Thanks for your time.

**Comment by thesobercoder** [comment]
@SimonCropp Please close this issue. After reverting to stable release packages everything was working fine.

**Comment by STRATZ-Ken** [comment]
I have been migrating to the new preview for GraphQL 3.0 as well.

I think I have been OK up until a similar point. Since the change of the Schema format : https://github.com/graphql-dotnet/examples/blob/master/src/StarWars/StarWarsSchema.cs

I am now unable to use GraphQL.EntityFramework 

>  {"Cannot resolve scoped service 'DbContext' from root provider."}
