### ISSUE TITLE
KeyNameExtractor creates collisions with many-to-many relationship

### ISSUE THREAD

**Issue by saltatory** [SimonCropp/GraphQL.EntityFramework#650]
# Description

The `KeyNameExtractor` creates a Dictionary of types - classes that encode an EF entity - and their keys. There have been several scenarios where this class results in name collisions. In the current scenario, I have more than one many-to-many relationship between two tables where the inferred join table is implicit rather than explicit. The key to the dictionary is the `EntityType.ClrType` which gets resolved to the exact same generic type. This results in a collision. The error appears during Depencency Injection - rather than compilation - when the framework is resolving services.

# Reproduction steps

## Create entities as follows

```csharp

class User {

        public List<Practice> PracticesEdited { get; set; } = new List<Practice>();

        public List<Practice> PracticesAdministered { get; set; } = new List<Practice>();

        public List<Practice> PracticesOwned { get; set; } = new List<Practice>();
}

class Practice {

        public User? Owner { get; set; } 

        public List<User> Administrators { get; set; } = new List<User>();

        public List<User> Editors { get; set; } = new List<User>();

}
```

## Register entity types and relationships with the DbContext

In the Db Context, register many-to-many relationships as follows

**Note** the User < - > Owner relationship is 1..1* but is here for clarity

```csharp
            modelBuilder.Entity<Practice>()
                .HasMany(x => x.Administrators)
                .WithMany(x =>x.PracticesAdministered);

            modelBuilder.Entity<Practice>()
                .HasMany(x => x.Editors)
                .WithMany(x => x.PracticesEdited);

            modelBuilder.Entity<Practice>()
                .HasOne<User>(x => x.Owner!)
                .WithMany(x => x.PracticesOwned);
```

## Execute any query

Upon first run of any query, the following error with stacktrace will be emitted:

```
     System.ArgumentException: An item with the same key has already been added. Key: System.Collections.Generic.Dictionary`2[System.String,System.Object]
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at KeyNameExtractor.GetKeyNames(IModel model) in /_/src/GraphQL.EntityFramework/KeyNameExtractor.cs:line 27
         at GraphQL.EntityFramework.EfGraphQLService`1..ctor(IModel model, ResolveDbContext`1 resolveDbContext, ResolveFilters resolveFilters, Boolean disableTracking) in /_/src/GraphQL.EntityFramework/GraphApi/EfGraphQLService.cs:line 32
         at GraphQL.EntityFramework.EfGraphQLConventions.Build[TDbContext](ResolveDbContext`1 dbContextResolver, IModel model, ResolveFilters filters, IServiceProvider provider, Boolean disableTracking) in /_/src/GraphQL.EntityFramework/EfGraphQLConventions.cs:line 55
         at GraphQL.EntityFramework.EfGraphQLConventions.<>c__DisplayClass0_0`1.<RegisterInContainer>b__0(IServiceProvider provider) in /_/src/GraphQL.EntityFramework/EfGraphQLConventions.cs:line 40
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 136
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The top of the stacktrace is indicating that multiple entities are getting resolved to the same `EntityType.ClrType` which is ``System.Collections.Generic.Dictionary`2[System.String,System.Object]``. 

# Proposed Solution For Discussion

I suspect that this exact issue would occur with any scenario that uses generic types. I believe I encountered this issue earlier when I was trying to use generics. I abandoned generics in the entity classes due to this.

It appears that a good solution to this issue would be to replace `EntityType.ClrType` with `EntityType.Name` but I wanted to solicit advice before proceeding.

**Comment by SimonCropp** [comment]
can u submit a failing unit test as a pull request that illustrates this problem
